# Generated by Django 2.2.3 on 2019-07-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='calendar_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feed',
            name='profile',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
