# Generated by Django 2.2.3 on 2019-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeri', '0002_auto_20190727_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_feed_id',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='calendars', to='cheeri.Feed'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='feed', to='cheeri.Event'),
        ),
    ]
