# Generated by Django 2.2.3 on 2019-07-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheeri', '0004_feed_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='feed',
            field=models.ForeignKey(blank=True, default='e62ac16e-41a9-46af-8807-bc40201fcf1d', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cheeri.Event'),
            preserve_default=False,
        ),
    ]
