# Generated by Django 2.2.3 on 2019-07-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeri', '0007_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(default='Technology', max_length=200),
            preserve_default=False,
        ),
    ]
